arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

# PID gains for each joint
/gazebo_ros_control/pid_gains/joint1:
  p: 1.0
  i: 0.01
  d: 0.1
  i_clamp: 0.1

/gazebo_ros_control/pid_gains/joint2:
  p: 1.0
  i: 0.01
  d: 0.1
  i_clamp: 0.1

/gazebo_ros_control/pid_gains/joint3:
  p: 1.0
  i: 0.01
  d: 0.1
  i_clamp: 0.1

/gazebo_ros_control/pid_gains/joint4:
  p: 1.0
  i: 0.01
  d: 0.1
  i_clamp: 0.1

/gazebo_ros_control/pid_gains/joint5:
  p: 1.0
  i: 0.01
  d: 0.1
  i_clamp: 0.1

/gazebo_ros_control/pid_gains/joint6:
  p: 1.0
  i: 0.01
  d: 0.1
  i_clamp: 0.1